const seed=[{"id": "OL-001", "title": "B-M", "author": "Founding dataset", "oakType": "B-M", "toast": "Medium", "preparation": "", "abv": null, "volume": null, "dose": null, "duration": null, "temperature": null, "sourceId": "", "notes": "Initial founding entry. Complete from original lab notes before public release."}, {"id": "OL-002", "title": "B-M+", "author": "Founding dataset", "oakType": "B-M+", "toast": "Medium+", "preparation": "", "abv": null, "volume": null, "dose": null, "duration": null, "temperature": null, "sourceId": "", "notes": "Initial founding entry."}, {"id": "OL-003", "title": "C-Light", "author": "Founding dataset", "oakType": "C-Light", "toast": "Light", "preparation": "", "abv": null, "volume": null, "dose": null, "duration": null, "temperature": null, "sourceId": "", "notes": "Initial founding entry."}, {"id": "OL-004", "title": "C-M", "author": "Founding dataset", "oakType": "C-M", "toast": "Medium", "preparation": "", "abv": null, "volume": null, "dose": null, "duration": null, "temperature": null, "sourceId": "", "notes": "Initial founding entry."}, {"id": "OL-005", "title": "A-HC", "author": "Founding dataset", "oakType": "A-HC", "toast": "Char", "preparation": "", "abv": null, "volume": null, "dose": null, "duration": null, "temperature": null, "sourceId": "", "notes": "Initial founding entry."}, {"id": "OL-006", "title": "A-Light", "author": "Founding dataset", "oakType": "A-Light", "toast": "Light", "preparation": "", "abv": null, "volume": null, "dose": null, "duration": null, "temperature": null, "sourceId": "", "notes": "Initial founding entry."}, {"id": "OL-007", "title": "АН", "author": "Founding dataset", "oakType": "АН", "toast": "Medium", "preparation": "", "abv": null, "volume": null, "dose": null, "duration": null, "temperature": null, "sourceId": "", "notes": "Initial founding entry."}, {"id": "OL-008", "title": "A-M+", "author": "Founding dataset", "oakType": "A-M+", "toast": "Medium+", "preparation": "48 h soaking; 30 min boiling", "abv": null, "volume": null, "dose": null, "duration": null, "temperature": null, "sourceId": "", "notes": "Preparation recorded from the current project notes; other parameters remain unfilled until verified."}];
let data=JSON.parse(localStorage.getItem('oaklab')||'null')||seed;
const $=s=>document.querySelector(s);
function save(){localStorage.setItem('oaklab',JSON.stringify(data))}
function render(){
 const q=$('#q').value.toLowerCase(),t=$('#toast').value;
 const a=data.filter(x=>(!q||JSON.stringify(x).toLowerCase().includes(q))&&(!t||x.toast===t));
 $('#count').textContent=a.length+' shown';
 $('#list').innerHTML=a.length?a.map(x=>`<article class="card"><h3>${esc(x.title)}</h3><div class="meta">${esc(x.oakType)} · ${esc(x.toast)} · ${esc(x.author)}</div><div class="chips">${x.abv?`<span class="chip">${x.abv}% ABV</span>`:''}${x.dose?`<span class="chip">${x.dose} g/L</span>`:''}${x.duration?`<span class="chip">${x.duration} days</span>`:''}</div><small>${data.filter(y=>y.sourceId===x.id).length} replication(s)</small><p>${esc(x.notes||'')}</p></article>`).join(''):'<div class="empty">No matching experiments.</div>';
 const authors=new Set(data.map(x=>x.author));
 $('#stats').innerHTML=`<div class="stat"><b>${data.length}</b><span>experiments</span></div><div class="stat"><b>${authors.size}</b><span>contributors</span></div><div class="stat"><b>${data.filter(x=>x.sourceId).length}</b><span>replications</span></div>`;
}
function esc(v){return String(v??'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
$('#q').oninput=render;$('#toast').onchange=render;
$('#new').onclick=()=>$('#dlg').showModal();$('#close').onclick=()=>$('#dlg').close();$('#cancel').onclick=()=>$('#dlg').close();
$('#form').onsubmit=e=>{e.preventDefault();let f=Object.fromEntries(new FormData(e.target));f.id='OL-'+Date.now().toString().slice(-7);for(const k of ['abv','volume','dose','duration','temperature'])f[k]=f[k]===''?null:Number(f[k]);data.unshift(f);save();e.target.reset();$('#dlg').close();render()};
$('#export').onclick=()=>{let b=new Blob([JSON.stringify({schemaVersion:1,experiments:data},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='oaklab-data.json';a.click()};
render();