let data=[];
const $=s=>document.querySelector(s);
let lang=localStorage.getItem("oaklab-language")||"ru";
const selectedIds=new Set();

const I={
ru:{subtitle:"Открытая база экспериментов с дубом",language:"Язык",compare:"Сравнить",selectForCompare:"Выбрать",selected:"Выбрано",newExp:"+ Новый эксперимент",hero:"Делись. Воспроизводи. Сравнивай.",intro:"Структурированная открытая база экспериментов с дубовой выдержкой и настаиванием.",search:"Поиск экспериментов…",allToast:"Все степени обжарки",export:"Экспорт JSON",experiments:"Эксперименты",shown:"показано",contributors:"участников",replications:"репликаций",view:"Открыть эксперимент",detail:"Эксперимент",oak:"Дуб",liquid:"Жидкость и экстракция",observations:"Наблюдения",tastings:"Дегустационные сессии",evidence:"Репликация и источники",color:"Цвет",srm:"Цвет (SRM)",hex:"HEX",rgb:"RGB",colorDb:"Цвет из базы данных",compareWith:"Сравнение цвета образцов",compareTitle:"Сравнение дегустаций",sample:"Образец",order:"Порядок",total:"Итог",overall:"Общее",title:"Название",author:"Автор",oakType:"Тип дуба",toast:"Обжарка",oakForm:"Форма дуба",chips:"Щепа",cubes:"Кубики",stave:"Планка",other:"Другое",volume:"Объём мл",dose:"Доза дуба г/л",duration:"Длительность, дней",temperature:"Температура °C",soaking:"Замачивание",boiling:"Кипячение",sourceId:"ID исходного эксперимента",notes:"Заметки",newTitle:"Новый эксперимент",cancel:"Отмена",create:"Создать локальный черновик",base:"Основа",abv:"ABV",container:"Ёмкость",agitation:"Перемешивание",type:"Тип",form:"Форма",species:"Порода",origin:"Происхождение",particle:"Размер частиц",rinsing:"Промывка",drying:"Сушка",prep:"Заметки подготовки",extraction:"Заметки экстракции",appearance:"Внешний вид",aroma:"Аромат",taste:"Вкус",mouthfeel:"Тактильное ощущение",overallNotes:"Общие заметки",sourceExp:"Исходный эксперимент",sourceNotes:"Заметки источника",firstTasting:"Дегустация",aging:"Выдержка",days:"дней",noData:"Нет подходящих экспериментов.",loadError:"Не удалось загрузить публичный набор данных."},
en:{subtitle:"Open oak experiment database",language:"Language",compare:"Compare",selectForCompare:"Select",selected:"Selected",newExp:"+ New experiment",hero:"Share. Reproduce. Compare.",intro:"A structured open database for oak infusion and aging experiments.",search:"Search experiments…",allToast:"All toast levels",export:"Export JSON",experiments:"Experiments",shown:"shown",contributors:"contributors",replications:"replications",view:"View experiment",detail:"Experiment",oak:"Oak",liquid:"Liquid & extraction",observations:"Observations",tastings:"Tasting sessions",evidence:"Replication & evidence",color:"Color",srm:"Color (SRM)",hex:"HEX",rgb:"RGB",colorDb:"Color from database",compareWith:"Sample color comparison",compareTitle:"Tasting comparison",sample:"Sample",order:"Order",total:"Total",overall:"Overall",title:"Title",author:"Author",oakType:"Oak type",toast:"Toast",oakForm:"Oak form",chips:"Chips",cubes:"Cubes",stave:"Stave",other:"Other",volume:"Volume ml",dose:"Oak dose g/L",duration:"Duration days",temperature:"Temperature °C",soaking:"Soaking",boiling:"Boiling",sourceId:"Source experiment ID",notes:"Notes",newTitle:"New experiment",cancel:"Cancel",create:"Create local draft",base:"Base",abv:"ABV",container:"Container",agitation:"Agitation",type:"Type",form:"Form",species:"Species",origin:"Origin",particle:"Particle size",rinsing:"Rinsing",drying:"Drying",prep:"Preparation notes",extraction:"Extraction notes",appearance:"Appearance",aroma:"Aroma",taste:"Taste",mouthfeel:"Mouthfeel",overallNotes:"Overall notes",sourceExp:"Source experiment",sourceNotes:"Source notes",firstTasting:"Tasting",aging:"Aging",days:"days",noData:"No matching experiments.",loadError:"The public dataset could not be loaded."},
de:{subtitle:"Offene Datenbank für Eichenexperimente",language:"Sprache",compare:"Vergleichen",selectForCompare:"Auswählen",selected:"Ausgewählt",newExp:"+ Neues Experiment",hero:"Teilen. Reproduzieren. Vergleichen.",intro:"Strukturierte offene Datenbank für Eicheninfusion und Reifung.",search:"Experimente suchen…",allToast:"Alle Röstgrade",export:"JSON exportieren",experiments:"Experimente",shown:"angezeigt",contributors:"Mitwirkende",replications:"Replikationen",view:"Experiment öffnen",detail:"Experiment",oak:"Eiche",liquid:"Flüssigkeit & Extraktion",observations:"Beobachtungen",tastings:"Verkostungen",evidence:"Replikation & Quellen",color:"Farbe",srm:"Farbe (SRM)",hex:"HEX",rgb:"RGB",colorDb:"Farbe aus der Datenbank",compareWith:"Farbvergleich der Muster",compareTitle:"Verkostungsvergleich",sample:"Muster",order:"Reihenfolge",total:"Gesamt",overall:"Gesamteindruck",title:"Titel",author:"Autor",oakType:"Eichenart",toast:"Röstung",oakForm:"Eichenform",chips:"Chips",cubes:"Würfel",stave:"Stave",other:"Andere",volume:"Volumen ml",dose:"Eichendosis g/L",duration:"Dauer Tage",temperature:"Temperatur °C",soaking:"Einweichen",boiling:"Kochen",sourceId:"Quell-Experiment-ID",notes:"Notizen",newTitle:"Neues Experiment",cancel:"Abbrechen",create:"Lokalen Entwurf erstellen",base:"Basis",abv:"ABV",container:"Behälter",agitation:"Bewegung",type:"Typ",form:"Form",species:"Art",origin:"Herkunft",particle:"Partikelgröße",rinsing:"Spülen",drying:"Trocknen",prep:"Vorbereitungsnotizen",extraction:"Extraktionsnotizen",appearance:"Aussehen",aroma:"Aroma",taste:"Geschmack",mouthfeel:"Mundgefühl",overallNotes:"Gesamtnotizen",sourceExp:"Quell-Experiment",sourceNotes:"Quellnotizen",firstTasting:"Verkostung",aging:"Reifung",days:"Tage",noData:"Keine passenden Experimente.",loadError:"Der öffentliche Datensatz konnte nicht geladen werden."},
fr:{subtitle:"Base ouverte d'expériences sur le chêne",language:"Langue",compare:"Comparer",selectForCompare:"Sélectionner",selected:"Sélectionnés",newExp:"+ Nouvelle expérience",hero:"Partager. Reproduire. Comparer.",intro:"Base ouverte structurée pour les expériences au chêne.",search:"Rechercher des expériences…",allToast:"Tous les niveaux de chauffe",export:"Exporter JSON",experiments:"Expériences",shown:"affichées",contributors:"contributeurs",replications:"réplications",view:"Ouvrir l'expérience",detail:"Expérience",oak:"Chêne",liquid:"Liquide et extraction",observations:"Observations",tastings:"Dégustations",evidence:"Réplication et sources",color:"Couleur",srm:"Couleur (SRM)",hex:"HEX",rgb:"RVB",colorDb:"Couleur de la base",compareWith:"Comparaison des couleurs",compareTitle:"Comparaison des dégustations",sample:"Échantillon",order:"Ordre",total:"Total",overall:"Global",title:"Titre",author:"Auteur",oakType:"Type de chêne",toast:"Chauffe",oakForm:"Forme",chips:"Copeaux",cubes:"Cubes",stave:"Douelle",other:"Autre",volume:"Volume ml",dose:"Dose de chêne g/L",duration:"Durée jours",temperature:"Température °C",soaking:"Trempage",boiling:"Ébullition",sourceId:"ID source",notes:"Notes",newTitle:"Nouvelle expérience",cancel:"Annuler",create:"Créer un brouillon local",base:"Base",abv:"ABV",container:"Récipient",agitation:"Agitation",type:"Type",form:"Forme",species:"Espèce",origin:"Origine",particle:"Taille des particules",rinsing:"Rinçage",drying:"Séchage",prep:"Notes de préparation",extraction:"Notes d'extraction",appearance:"Aspect",aroma:"Arôme",taste:"Goût",mouthfeel:"Sensation en bouche",overallNotes:"Notes générales",sourceExp:"Expérience source",sourceNotes:"Notes source",firstTasting:"Dégustation",aging:"Vieillissement",days:"jours",noData:"Aucune expérience correspondante.",loadError:"Impossible de charger les données."},
es:{subtitle:"Base abierta de experimentos con roble",language:"Idioma",compare:"Comparar",selectForCompare:"Seleccionar",selected:"Seleccionados",newExp:"+ Nuevo experimento",hero:"Comparte. Reproduce. Compara.",intro:"Base abierta estructurada para experimentos con roble.",search:"Buscar experimentos…",allToast:"Todos los niveles de tostado",export:"Exportar JSON",experiments:"Experimentos",shown:"mostrados",contributors:"colaboradores",replications:"replicaciones",view:"Abrir experimento",detail:"Experimento",oak:"Roble",liquid:"Líquido y extracción",observations:"Observaciones",tastings:"Catas",evidence:"Replicación y fuentes",color:"Color",srm:"Color (SRM)",hex:"HEX",rgb:"RGB",colorDb:"Color de la base",compareWith:"Comparación de colores",compareTitle:"Comparación de catas",sample:"Muestra",order:"Orden",total:"Total",overall:"General",title:"Título",author:"Autor",oakType:"Tipo de roble",toast:"Tostado",oakForm:"Forma",chips:"Virutas",cubes:"Cubos",stave:"Listón",other:"Otro",volume:"Volumen ml",dose:"Dosis de roble g/L",duration:"Duración días",temperature:"Temperatura °C",soaking:"Remojo",boiling:"Hervido",sourceId:"ID de origen",notes:"Notas",newTitle:"Nuevo experimento",cancel:"Cancelar",create:"Crear borrador local",base:"Base",abv:"ABV",container:"Recipiente",agitation:"Agitación",type:"Tipo",form:"Forma",species:"Especie",origin:"Origen",particle:"Tamaño de partícula",rinsing:"Enjuague",drying:"Secado",prep:"Notas de preparación",extraction:"Notas de extracción",appearance:"Aspecto",aroma:"Aroma",taste:"Sabor",mouthfeel:"Sensación en boca",overallNotes:"Notas generales",sourceExp:"Experimento de origen",sourceNotes:"Notas de origen",firstTasting:"Cata",aging:"Envejecimiento",days:"días",noData:"No hay experimentos coincidentes.",loadError:"No se pudieron cargar los datos."},
it:{subtitle:"Database aperto degli esperimenti con rovere",language:"Lingua",compare:"Confronta",selectForCompare:"Seleziona",selected:"Selezionati",newExp:"+ Nuovo esperimento",hero:"Condividi. Riproduci. Confronta.",intro:"Database aperto strutturato per esperimenti con rovere.",search:"Cerca esperimenti…",allToast:"Tutti i livelli di tostatura",export:"Esporta JSON",experiments:"Esperimenti",shown:"visualizzati",contributors:"collaboratori",replications:"repliche",view:"Apri esperimento",detail:"Esperimento",oak:"Rovere",liquid:"Liquido ed estrazione",observations:"Osservazioni",tastings:"Degustazioni",evidence:"Replica e fonti",color:"Colore",srm:"Colore (SRM)",hex:"HEX",rgb:"RGB",colorDb:"Colore dal database",compareWith:"Confronto dei colori",compareTitle:"Confronto degustazioni",sample:"Campione",order:"Ordine",total:"Totale",overall:"Complessivo",title:"Titolo",author:"Autore",oakType:"Tipo di rovere",toast:"Tostatura",oakForm:"Forma",chips:"Scaglie",cubes:"Cubetti",stave:"Listello",other:"Altro",volume:"Volume ml",dose:"Dose rovere g/L",duration:"Durata giorni",temperature:"Temperatura °C",soaking:"Ammollo",boiling:"Bollitura",sourceId:"ID origine",notes:"Note",newTitle:"Nuovo esperimento",cancel:"Annulla",create:"Crea bozza locale",base:"Base",abv:"ABV",container:"Contenitore",agitation:"Agitazione",type:"Tipo",form:"Forma",species:"Specie",origin:"Origine",particle:"Dimensione particelle",rinsing:"Risciacquo",drying:"Asciugatura",prep:"Note di preparazione",extraction:"Note di estrazione",appearance:"Aspetto",aroma:"Aroma",taste:"Gusto",mouthfeel:"Sensazione al palato",overallNotes:"Note generali",sourceExp:"Esperimento origine",sourceNotes:"Note fonte",firstTasting:"Degustazione",aging:"Affinamento",days:"giorni",noData:"Nessun esperimento corrispondente.",loadError:"Impossibile caricare i dati."},
pt:{subtitle:"Base aberta de experiências com carvalho",language:"Idioma",compare:"Comparar",newExp:"+ Nova experiência",hero:"Partilhe. Reproduza. Compare.",intro:"Base aberta estruturada para experiências com carvalho.",search:"Pesquisar experiências…",allToast:"Todos os níveis de tosta",export:"Exportar JSON",experiments:"Experiências",shown:"mostradas",contributors:"colaboradores",replications:"replicações",view:"Abrir experiência",detail:"Experiência",oak:"Carvalho",liquid:"Líquido e extração",observations:"Observações",tastings:"Degustações",evidence:"Replicação e fontes",color:"Cor",srm:"Cor (SRM)",hex:"HEX",rgb:"RGB",colorDb:"Cor da base de dados",compareWith:"Comparação das cores",compareTitle:"Comparação de degustações",sample:"Amostra",order:"Ordem",total:"Total",overall:"Geral",title:"Título",author:"Autor",oakType:"Tipo de carvalho",toast:"Tosta",oakForm:"Forma",chips:"Aparas",cubes:"Cubos",stave:"Tábua",other:"Outro",volume:"Volume ml",dose:"Dose de carvalho g/L",duration:"Duração dias",temperature:"Temperatura °C",soaking:"Demolha",boiling:"Fervura",sourceId:"ID de origem",notes:"Notas",newTitle:"Nova experiência",cancel:"Cancelar",create:"Criar rascunho local",base:"Base",abv:"ABV",container:"Recipiente",agitation:"Agitação",type:"Tipo",form:"Forma",species:"Espécie",origin:"Origem",particle:"Tamanho das partículas",rinsing:"Enxaguamento",drying:"Secagem",prep:"Notas de preparação",extraction:"Notas de extração",appearance:"Aspeto",aroma:"Aroma",taste:"Sabor",mouthfeel:"Sensação na boca",overallNotes:"Notas gerais",sourceExp:"Experiência de origem",sourceNotes:"Notas de origem",firstTasting:"Degustação",aging:"Envelhecimento",days:"dias",noData:"Nenhuma experiência correspondente.",loadError:"Não foi possível carregar os dados."}
};
const t=k=>(I[lang]||I.ru)[k]||I.ru[k]||k;
const esc=v=>String(v??"").replace(/[&<>"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[m]));
function color(x){return x.observations?.color||null}
function glass(x,large=false){
 const c=color(x); if(!c)return "";
 return '<div class="wine-glass '+(large?"large":"")+'" aria-label="'+esc(t("color"))+' '+esc(c.hex)+'"><div class="bowl"><div class="liquid" style="background:'+esc(c.hex)+'"></div><div class="shine"></div></div><div class="stem"></div><div class="foot"></div></div>';
}
function colorPanel(x){
 const c=color(x);if(!c)return "";
 const others=data.filter(y=>color(y));
 return '<section class="color-panel"><h3>'+t("color")+'</h3><div class="color-record"><div class="glass-stage">'+glass(x,true)+'</div><div class="color-info"><div class="color-db-label">'+t("colorDb")+'</div><div class="color-values"><div><small>'+t("srm")+'</small><b>'+esc(c.srm??"—")+'</b></div><div><small>'+t("hex")+'</small><b>'+esc(c.hex??"—")+'</b></div><div><small>'+t("rgb")+'</small><b>'+esc(c.rgb??"—")+'</b></div></div><div class="color-caption">'+esc(c.source||"")+'</div></div></div><div class="color-compare-title">'+t("compareWith")+'</div><div class="color-glasses">'+others.map(y=>'<div class="color-sample '+(y.id===x.id?"selected":"")+'">'+glass(y,false)+'<span>'+esc(y.title)+'</span></div>').join("")+'</div></section>';
}
function applyLanguage(){
 document.documentElement.lang=lang;
 document.querySelectorAll("[data-i18n]").forEach(e=>e.textContent=t(e.dataset.i18n));
 document.querySelectorAll("[data-i18n-placeholder]").forEach(e=>e.placeholder=t(e.dataset.i18nPlaceholder));
 $("#language").value=lang;$("#language").setAttribute("aria-label",t("language"));
 $("#toast").options[0].textContent=t("allToast");
 render();
}
async function load(){
 try{const r=await fetch("data.json",{cache:"no-store"});if(!r.ok)throw Error();const j=await r.json();data=await Promise.all((j.experiments||[]).map(async m=>{const r=await fetch(m.path,{cache:"no-store"});if(!r.ok)throw Error(m.path);return r.json()}));}
 catch(e){console.error(e);data=[];$("#list").innerHTML='<div class="empty">'+t("loadError")+"</div>"}render();
}
function render(){
 updateCompareButton();
 const q=$("#q").value.trim().toLowerCase(),toast=$("#toast").value;
 const a=data.filter(x=>(!q||JSON.stringify(x).toLowerCase().includes(q))&&(!toast||x.oak?.toast===toast));
 $("#count").textContent=a.length+" "+t("shown");
 $("#list").innerHTML=a.length?a.map(card).join(""):'<div class="empty">'+t("noData")+"</div>";
 const authors=new Set(data.map(x=>x.author).filter(Boolean)),reps=data.filter(x=>x.replication?.sourceId).length;
 $("#stats").innerHTML='<div class="stat"><b>'+data.length+'</b><span>'+t("experiments").toLowerCase()+'</span></div><div class="stat"><b>'+authors.size+'</b><span>'+t("contributors")+'</span></div><div class="stat"><b>'+reps+'</b><span>'+t("replications")+'</span></div>';
}
function card(x){
 const c=color(x),children=data.filter(y=>y.replication?.sourceId===x.id).length;
 let chips="";
 if(x.oak?.toast)chips+=`<span class="chip">${esc(x.oak.toast)}</span>`;
 if(x.liquid?.abv!=null)chips+=`<span class="chip">${x.liquid.abv}% ABV</span>`;
 if(x.extraction?.doseGPerL!=null)chips+=`<span class="chip">${x.extraction.doseGPerL} g/L</span>`;
 if(x.extraction?.durationDays!=null)chips+=`<span class="chip">${x.extraction.durationDays} ${t("days")}</span>`;
 return `<article class="card">
   <label class="card-select"><input type="checkbox" class="compare-check" data-id="${esc(x.id)}" ${selectedIds.has(x.id)?"checked":""}><span>${t("selectForCompare")}</span></label>
   <div class="card-top">${c?glass(x,false):""}<div><h3>${esc(x.title)}</h3><div class="meta">${esc(x.oak?.type||"")} · ${esc(x.oak?.form||"")} · ${esc(x.author||"")}</div></div></div>
   <div class="chips">${chips}</div>
   ${x.replication?.sourceId?`<div class="meta">↳ ${esc(x.replication.sourceId)}</div>`:""}
   <small>${children} ${t("replications")}</small>
   <p>${esc(x.observations?.overallNotes||"")}</p>
   <button class="open" data-id="${esc(x.id)}">${t("view")}</button>
 </article>`;
}
function details(x){
 const p=x.oak?.preparation||{},e=x.extraction||{},l=x.liquid||{},o=x.observations||{},ts=x.tastingSessions||[];
 const row=(label,v,unit="")=>v!=null&&v!==""?`<div><dt>${label}</dt><dd>${esc(v)}${unit}</dd></div>`:"";
 const scoreLabels={aroma:"Аромат",softness:"Мягкость",oak:"Дуб / древесность",vanilla:"Ваниль",caramelToast:"Карамель / обжарка",fruitNut:"Сухофрукты / орехи",smokeChar:"Дым / обугленность",spirit:"Спиртуозность",bitterness:"Горечь",astringency:"Терпкость"};
 const tasting=ts.map(v=>`<h3>${t("firstTasting")} — ${esc(v.date||"")}</h3><div class="meta">${t("order")}: ${esc(v.order??"—")} · ${t("aging")}: ${esc(v.agingDays??"—")} ${t("days")} · ${t("total")}: ${esc(v.total??"—")}/50 · ${t("overall")}: ${esc(v.overall??"—")}/10</div><dl>${Object.entries(scoreLabels).map(([k,n])=>row(n,v.scores?.[k])).join("")}</dl>${row(t("notes"),v.notes)}`).join("");
 $("#detailBody").innerHTML=`<div class="detail-scroll">
   <div class="detailtitle"><span class="chip">${esc(x.status)}</span><span class="meta">${esc(x.id)}</span></div>
   <h2>${esc(x.title)}</h2><p class="meta">${esc(x.author||"")}</p>
   ${colorPanel(x)}
   <h3>${t("oak")}</h3><dl>${row(t("type"),x.oak?.type)}${row(t("form"),x.oak?.form)}${row(t("species"),x.oak?.species)}${row(t("origin"),x.oak?.origin)}${row(t("particle"),x.oak?.particleSize)}${row(t("toast"),x.oak?.toast)}${row(t("soaking"),p.soaking)}${row(t("boiling"),p.boiling)}${row(t("rinsing"),p.rinsing)}${row(t("drying"),p.drying)}${row(t("prep"),p.notes)}</dl>
   <h3>${t("liquid")}</h3><dl>${row(t("base"),l.base)}${row(t("abv"),l.abv,"%")}${row(t("volume"),l.volumeMl," ml")}${row(t("dose"),e.doseGPerL," g/L")}${row(t("duration"),e.durationDays," "+t("days"))}${row(t("temperature"),e.temperatureC," °C")}${row(t("container"),e.container)}${row(t("agitation"),e.agitation)}${row(t("extraction"),e.notes)}</dl>
   <h3>${t("observations")}</h3><dl>${row(t("appearance"),o.appearance)}${row(t("aroma"),o.aroma)}${row(t("taste"),o.taste)}${row(t("mouthfeel"),o.mouthfeel)}${row(t("overallNotes"),o.overallNotes)}</dl>
   ${tasting?`<h3>${t("tastings")}</h3>${tasting}`:""}
   <h3>${t("evidence")}</h3><dl>${row(t("sourceExp"),x.replication?.sourceId)}${row(t("sourceNotes"),x.evidence?.sourceNotes)}</dl>
 </div>`;
 $("#detail").showModal();
}
function updateCompareButton(){const n=selectedIds.size;$("#compare").textContent=n? t("compare")+" ("+n+")":t("compare")}
function compare(){
 const rows=data.filter(x=>selectedIds.has(x.id)).map(x=>({x,t:(x.tastingSessions||[]).slice(-1)[0]})).filter(v=>v.t).sort((a,b)=>(a.t.order??999)-(b.t.order??999));
 const keys=["aroma","spirit","softness","oak","vanilla","caramelToast","fruitNut","smokeChar","bitterness","astringency"];
 const names=["Аромат","Спиртуозность","Мягкость","Дуб","Ваниль","Карамель","Сухофрукты","Дым","Горечь","Терпкость"];
 const body=rows.map(({x,t})=>'<tr><td>'+esc(x.title)+'</td><td>'+esc(t.order??"—")+'</td>'+keys.map(k=>'<td>'+esc(t.scores?.[k]??"—")+"</td>").join("")+'<td><b>'+esc(t.total??"—")+"/50</b></td><td><b>"+esc(t.overall??"—")+"/10</b></td></tr>").join("");
 if(!rows.length){$("#compareBody").innerHTML="<p class=\"compare-note\">"+t("selectForCompare")+": 1 "+t("sample")+"</p>";$("#compareDlg").showModal();return;} $("#compareBody").innerHTML='<div class="compare-scroll"><table class="compare-table"><thead><tr><th>'+t("sample")+'</th><th>'+t("order")+'</th>'+names.map(n=>"<th>"+n+"</th>").join("")+"<th>"+t("total")+"</th><th>"+t("overall")+"</th></tr></thead><tbody>"+body+"</tbody></table></div>";
 $("#compareDlg").showModal();
}
function num(v){return v===""?null:Number(v)}
$("#language").onchange=e=>{lang=e.target.value;localStorage.setItem("oaklab-language",lang);applyLanguage()};
$("#q").oninput=render;$("#toast").onchange=render;$("#compare").onclick=compare;
$("#list").addEventListener("change",e=>{const box=e.target.closest(".compare-check");if(!box)return;if(box.checked)selectedIds.add(box.dataset.id);else selectedIds.delete(box.dataset.id);updateCompareButton();});
$("#new").onclick=()=>$("#dlg").showModal();$("#close").onclick=()=>$("#dlg").close();$("#cancel").onclick=()=>$("#dlg").close();
$("#list").onclick=e=>{const b=e.target.closest(".open");if(b){const x=data.find(v=>v.id===b.dataset.id);if(x)details(x)}};
$("#form").onsubmit=e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));data.unshift({schemaVersion:2,id:"LOCAL-"+Date.now(),status:"draft",title:f.title,author:f.author,oak:{type:f.oakType,form:f.form,toast:f.toast,preparation:{soaking:f.soaking||null,boiling:f.boiling||null}},liquid:{abv:num(f.abv),volumeMl:num(f.volumeMl)},extraction:{doseGPerL:num(f.doseGPerL),durationDays:num(f.durationDays),temperatureC:num(f.temperatureC)},observations:{overallNotes:f.notes||null},replication:{sourceId:f.sourceId||null},tastingSessions:[]});e.target.reset();$("#dlg").close();render()};
$("#export").onclick=()=>{const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify({schemaVersion:2,experiments:data},null,2)],{type:"application/json"}));a.download="oaklab-data-v2.json";a.click()};
applyLanguage();load();